# Exploración datos

In [ ]:
# Llama a un archivo con nombre "01. clasificacion_datos_ml.xlsx" que esta en capeta data.

In [2]:
import pandas as pd

In [3]:
# llama el archivo data1 y esta en data.
df = pd.read_excel("data/data1.xlsx")

In [7]:
df.columns.tolist()

['id_registro',
 'fecha_registro',
 'edad',
 'ingreso_anual_usd',
 'puntaje_credito',
 'num_compras_mes',
 'segmento_cliente',
 'canal_preferido',
 'subscripcion_activa',
 'clasificacion_churn_ETIQUETA',
 'nivel_satisfaccion_ETIQUETA',
 'horas_sesion_semanal',
 'monto_promedio_gasto',
 'num_tickets_soporte',
 'comentario_feedback_TEXTO',
 'transcripcion_interaccion_TEXTO',
 'archivo_foto_id_URL',
 'archivo_audio_llamada_URL',
 'categoria_tipo_dato',
 'metodo_ml_aplicable']

In [9]:
# Mostrar las primeras 20 columnas
#print(df.columns[:20].tolist())
df.head(20)

,id_registro,fecha_registro,edad,ingreso_anual_usd,puntaje_credito,num_compras_mes,segmento_cliente,canal_preferido,subscripcion_activa,clasificacion_churn_ETIQUETA,nivel_satisfaccion_ETIQUETA,horas_sesion_semanal,monto_promedio_gasto,num_tickets_soporte,comentario_feedback_TEXTO,transcripcion_interaccion_TEXTO,archivo_foto_id_URL,archivo_audio_llamada_URL,categoria_tipo_dato,metodo_ml_aplicable
0,1001,2026-02-10,36.0,50098.0,694.0,9.0,Corporativo,App Móvil,Sí,0,Alto,9.5,254.94,0.0,Excelente servicio y atención al cliente muy r...,Usuario reporta bloqueo de cuenta por intento ...,s3://empresa-data/fotos_id/usr_1001.png,s3://empresa-data/audios_llamadas/call_1001_20...,Estructurado + No Estructurado,Supervisado / No Supervisado
1,1002,2026-09-16,64.0,103181.0,794.0,15.0,Pyme,Tienda Física,No,0,Alto,13.9,95.74,5.0,"Proceso de compra rápido, claro y sin complica...",Usuario solicita asistencia guiada para config...,s3://empresa-data/fotos_id/usr_1002.png,s3://empresa-data/audios_llamadas/call_1002_20...,Estructurado + No Estructurado,Supervisado / No Supervisado
2,1003,2026-02-12,43.0,30676.0,763.0,23.0,Corporativo,Plataforma Web,Sí,0,Alto,21.6,402.38,9.0,Cumple con lo prometido aunque la interfaz de ...,Usuario reporta bloqueo de cuenta por intento ...,s3://empresa-data/fotos_id/usr_1003.png,s3://empresa-data/audios_llamadas/call_1003_20...,Estructurado + No Estructurado,Supervisado / No Supervisado
3,1004,2026-06-28,31.0,110349.0,615.0,3.0,Corporativo,App Móvil,No,0,Alto,11.6,314.24,5.0,"La aplicación móvil funciona genial, estoy muy...",Usuario solicita asistencia guiada para config...,s3://empresa-data/fotos_id/usr_1004.png,s3://empresa-data/audios_llamadas/call_1004_20...,Estructurado + No Estructurado,Supervisado / No Supervisado
4,1005,2026-03-21,41.0,45460.0,716.0,5.0,Corporativo,Tienda Física,Sí,0,Alto,15.4,475.23,10.0,"Proceso de compra rápido, claro y sin complica...",Reporte de bug visual en la pestaña de ajustes...,s3://empresa-data/fotos_id/usr_1005.png,s3://empresa-data/audios_llamadas/call_1005_20...,Estructurado + No Estructurado,Supervisado / No Supervisado
5,1006,2026-09-17,62.0,60504.0,608.0,15.0,Individual,Plataforma Web,No,1,Bajo,9.3,252.15,10.0,"Muy decepcionado con el rendimiento, evaluaré ...",Solicitud de cancelación por cambio de presupu...,s3://empresa-data/fotos_id/usr_1006.png,s3://empresa-data/audios_llamadas/call_1006_20...,Estructurado + No Estructurado,Supervisado (Clasificación/NLP)
6,1007,2026-08-14,35.0,36301.0,706.0,35.0,Pyme,Tienda Física,No,0,Medio,37.9,87.94,7.0,El servicio es aceptable pero la app se siente...,Cliente manifiesta molestia por demora en entr...,s3://empresa-data/fotos_id/usr_1007.png,s3://empresa-data/audios_llamadas/call_1007_20...,Estructurado + No Estructurado,Supervisado / No Supervisado
7,1008,2026-02-11,26.0,38033.0,661.0,28.0,Corporativo,App Móvil,No,1,Medio,36.9,416.65,0.0,"Muy decepcionado con el rendimiento, evaluaré ...",Consulta técnica sobre límites de peticiones A...,s3://empresa-data/fotos_id/usr_1008.png,s3://empresa-data/audios_llamadas/call_1008_20...,Estructurado + No Estructurado,Supervisado (Clasificación/NLP)
8,1009,2026-02-27,36.0,118741.0,754.0,8.0,Pyme,Plataforma Web,Sí,0,Medio,20.0,73.42,10.0,"Plataforma funcional, aunque faltan algunas op...",Llamada solicitando aclaración sobre el desglo...,s3://empresa-data/fotos_id/usr_1009.png,s3://empresa-data/audios_llamadas/call_1009_20...,Estructurado + No Estructurado,Supervisado / No Supervisado
9,1010,2026-05-26,57.0,44071.0,658.0,24.0,Individual,Tienda Física,Sí,0,Medio,35.4,424.82,4.0,Excelente servicio y atención al cliente muy r...,Usuario reporta bloqueo de cuenta por intento ...,s3://empresa-data/fotos_id/usr_1010.png,s3://empresa-data/audios_llamadas/call_1010_20...,Estructurado + No Estructurado,Supervisado / No Supervisado
10,1011,2026-04-11,34.0,92364.0,620.0,6.0,Corporativo,Plataforma Web,Sí,0,Alto,36.1,100.13,8.0,"Proceso de compra rápido, claro y sin complica...",Reporte de bug visual en la pestaña de ajustes...,s3://empresa-data/fotos_id/usr_1011.png,s3://empresa-data/audios_llamadas/call_1011_20...,Estructurado + No Estructurado,Supervisado / No Supervisado
11,1012,2026-07-16,53.0,116994.0,682.0,20.0,Pyme,Tienda Física,No,1,Medio,9.7,178.83,9.0,"Pésima experiencia, la plataforma falló durant...",Cliente manifiesta molestia por demora en entr...,s3://empresa-data/fotos_id/usr_1012.png,s3://empresa-data/audios_llamadas/call_1012_20...,Estructurado + No Estructurado,Supervisado (Clasificación/NLP)
12,1013,2026-09-17,56.0,46864.0,583.0,5.0,Corporativo,Tienda Física,Sí,1,Bajo,20.3,151.71,7.0,No estoy conforme con los cobros de comisiones...,Usuario reporta bloqueo de cuenta por intento ...,s3://empresa-data/fotos_id/usr_1013.png,s3://empresa-data/audios_llamadas/call_1013_20...,Estructurado + No Estructurado,Supervisado (Clasificación/NLP)
13,1014,2026-04-27,27.0,112811.0,822.0,16.0,Pyme,Plataforma Web,Sí,1,Medio,16.5,418.05,0.0,No estoy conforme con los cobros de comisiones...,Usuario solicita asistencia guiada para config...,s3://empresa-data/fotos_id/usr_1014.png,s3://empresa-data/audios_llamadas/call_1014_20...,Estructurado + No Estructurado,Supervisado (Clasificación/NLP)
14,1015,2026-02-11,44.0,113448.0,753.0,7.0,Individual,App Móvil,Sí,0,Alto,11.7,138.66,1.0,Cumple con lo prometido aunque la interfaz de ...,Llamada solicitando aclaración sobre el desglo...,s3://empresa-data/fotos_id/usr_1015.png,s3://empresa-data/audios_llamadas/call_1015_20...,Estructurado + No Estructurado,Supervisado / No Supervisado
15,1016,2026-08-27,25.0,24630.0,587.0,6.0,Individual,App Móvil,No,1,Bajo,7.5,25.98,6.0,La interfaz es confusa y es difícil encontrar ...,Cliente solicita información sobre actualizaci...,s3://empresa-data/fotos_id/usr_1016.png,s3://empresa-data/audios_llamadas/call_1016_20...,Estructurado + No Estructurado,Supervisado (Clasificación/NLP)
16,1017,2026-05-24,37.0,73444.0,829.0,10.0,Individual,Plataforma Web,Sí,0,Alto,3.3,241.94,8.0,El servicio es aceptable pero la app se siente...,Cliente solicita información sobre actualizaci...,s3://empresa-data/fotos_id/usr_1017.png,s3://empresa-data/audios_llamadas/call_1017_20...,Estructurado + No Estructurado,Supervisado / No Supervisado
17,1018,2026-03-11,51.0,28500.0,675.0,5.0,Corporativo,App Móvil,Sí,1,Bajo,24.1,215.75,9.0,"Muy decepcionado con el rendimiento, evaluaré ...",Cliente solicita información sobre actualizaci...,s3://empresa-data/fotos_id/usr_1018.png,s3://empresa-data/audios_llamadas/call_1018_20...,Estructurado + No Estructurado,Supervisado (Clasificación/NLP)
18,1019,2026-09-20,35.0,44772.0,740.0,16.0,Pyme,Plataforma Web,Sí,0,Medio,35.4,450.76,0.0,"Atención estándar, sin inconvenientes relevant...",Solicitud de cancelación por cambio de presupu...,s3://empresa-data/fotos_id/usr_1019.png,s3://empresa-data/audios_llamadas/call_1019_20...,Estructurado + No Estructurado,Supervisado / No Supervisado
19,1020,2026-08-28,25.0,27602.0,689.0,33.0,Pyme,App Móvil,No,0,Alto,7.3,404.35,4.0,El servicio es aceptable pero la app se siente...,Consulta técnica sobre límites de peticiones A...,s3://empresa-data/fotos_id/usr_1020.png,s3://empresa-data/audios_llamadas/call_1020_20...,Estructurado + No Estructurado,Supervisado / No Supervisado

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101 entries, 0 to 100
Data columns (total 20 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   id_registro                      101 non-null    object
 1   fecha_registro                   101 non-null    object
 2   edad                             101 non-null    float64
 3   ingreso_anual_usd                101 non-null    float64
 4   puntaje_credito                  101 non-null    float64
 5   num_compras_mes                  101 non-null    float64
 6   segmento_cliente                 101 non-null    object
 7   canal_preferido                  101 non-null    object
 8   subscripcion_activa              101 non-null    object
 9   clasificacion_churn_ETIQUETA     101 non-null    int64
 10  nivel_satisfaccion_ETIQUETA      101 non-null    object
 11  horas_sesion_semanal             101 non-null    float64
 12  monto_promedio_gasto             101 non-null    float64
 13  num_tickets_soporte              101 non-null    float64
 14  comentario_feedback_TEXTO        101 non-null    object
 15  transcripcion_interaccion_TEXTO  101 non-null    object
 16  archivo_foto_id_URL              101 non-null    object
 17  archivo_audio_llamada_URL        101 non-null    object
 18  categoria_tipo_dato              101 non-null    object
 19  metodo_ml_aplicable              101 non-null    object
dtypes: float64(7), int64(1), object(12)
memory usage: 15.9+ KB

In [11]:
# últimos 5 registros
df.tail(5)

,id_registro,fecha_registro,edad,ingreso_anual_usd,puntaje_credito,num_compras_mes,segmento_cliente,canal_preferido,subscripcion_activa,clasificacion_churn_ETIQUETA,nivel_satisfaccion_ETIQUETA,horas_sesion_semanal,monto_promedio_gasto,num_tickets_soporte,comentario_feedback_TEXTO,transcripcion_interaccion_TEXTO,archivo_foto_id_URL,archivo_audio_llamada_URL,categoria_tipo_dato,metodo_ml_aplicable
96,1097,2026-03-24,21.0,71852.00,766.00,16.00,Pyme,Tienda Física,No,0,Medio,12.800,392.9200,7.00,"Muy buena experiencia general, recomendaré el ...",Cliente manifiesta molestia por demora en entr...,s3://empresa-data/fotos_id/usr_1097.png,s3://empresa-data/audios_llamadas/call_1097_20...,Estructurado + No Estructurado,Supervisado / No Supervisado
97,1098,2026-04-21,62.0,92766.00,805.00,30.00,Pyme,Plataforma Web,No,0,Alto,33.400,48.7400,7.00,"Uso el portal semanalmente, opera con normalid...",Llamada solicitando aclaración sobre el desglo...,s3://empresa-data/fotos_id/usr_1098.png,s3://empresa-data/audios_llamadas/call_1098_20...,Estructurado + No Estructurado,Supervisado / No Supervisado
98,1099,2026-06-27,25.0,111244.00,844.00,8.00,Pyme,App Móvil,Sí,0,Alto,36.000,126.0300,7.00,Cumple con lo prometido aunque la interfaz de ...,Usuario reporta bloqueo de cuenta por intento ...,s3://empresa-data/fotos_id/usr_1099.png,s3://empresa-data/audios_llamadas/call_1099_20...,Estructurado + No Estructurado,Supervisado / No Supervisado
99,1100,2026-06-10,45.0,24980.00,782.00,33.00,Pyme,App Móvil,No,0,Medio,13.100,70.0800,10.00,"Muy buena experiencia general, recomendaré el ...",Cliente solicita información sobre actualizaci...,s3://empresa-data/fotos_id/usr_1100.png,s3://empresa-data/audios_llamadas/call_1100_20...,Estructurado + No Estructurado,Supervisado / No Supervisado
100,PROMEDIO / TOTAL,-,40.8,67185.67,709.72,18.23,-,-,-,38,-,19.538,247.6822,5.36,-,-,-,-,-,-

In [12]:
# Estadística descriptiva de las variables numéricas
df.describe()

,edad,ingreso_anual_usd,puntaje_credito,num_compras_mes,clasificacion_churn_ETIQUETA,horas_sesion_semanal,monto_promedio_gasto,num_tickets_soporte
count,101.000000,101.000000,101.000000,101.000000,101.000000,101.000000,101.000000,101.000000
mean,40.800000,67185.670000,709.720000,18.230000,0.752475,19.538000,247.682200,5.360000
std,13.391789,31862.692847,77.239508,10.306168,3.774668,10.677629,128.911092,3.254289
min,20.000000,22852.000000,583.000000,1.000000,0.000000,2.100000,25.980000,0.000000
25%,28.000000,39747.000000,647.000000,7.000000,0.000000,10.800000,139.390000,3.000000
50%,38.000000,57139.000000,715.000000,19.000000,0.000000,17.900000,229.990000,5.360000
75%,52.000000,97997.000000,773.000000,27.000000,1.000000,28.900000,353.330000,8.000000
max,65.000000,124824.000000,847.000000,35.000000,38.000000,37.900000,475.230000,10.000000